### ISSUE TITLE
SPサイズでスクロールした際にヘッダーが途中で止まる

### ISSUE THREAD

**Issue by dsk52** [mismith0227/wp-theme-modernize#142]
SPサイズくらいまでウィンドウを縮めてスクロールした際、下へスクロールするときはついてくるが、上にスクロールした時に隠れず途中で止まる

adminバーが有るときだけ起こるので普通に見る分にはそこまで問題ない…かも？

(iPhone5/Safari, Chrome で確認)

**Comment by mismith0227** [comment]
adminバーある時みてなかった...。対応できそうだったらやろう

**Comment by dsk52** [comment]
この辺めんどそうなのでclose
